You can view this document @ http://bit.ly/himym-graph

= Neo4j London Meetup, 2nd June 2015:  The How I met your mother graph

In this session we'll be working with a graph of How I met your mother that I've scrapped from the link:http://how-i-met-your-mother.wikia.com/wiki/How_I_Met_Your_Mother_Wiki[HIMYM wiki].

The plan is to write some queries to explore the dataset and learn Neo4j’s cypher language at the same time. If we have time we can even look at how to merge some other data sets in as well.

== Setup

First things first, let's get Neo4j running on your machines.

* Download Neo4j from http://www.neo4j.com/download
* Windows users: Install desktop application & then click the 'start' button
*   Mac/Linux: Unpack archive & then `./bin/neo4j start`



== The Episodes

The first thing we need to do is load the episodes into Neo4j. I've already done the scrapping of the data into a CSV file so let's start by exploring that:

[source, cypher]
----
LOAD CSV WITH HEADERS FROM "https://raw.githubusercontent.com/mneedham/neo4j-himym/master/data/import/episodes_full.csv" AS row
RETURN row
LIMIT 1
----

Now that we've got an understanding of the shape of the data let's create an episode for each row in that file:

[source, cypher]
----
LOAD CSV WITH HEADERS FROM "https://raw.githubusercontent.com/mneedham/neo4j-himym/master/data/import/episodes_full.csv" AS row
MERGE (episode:Episode {id: TOINT(row.NumberOverall)})
SET episode.title = row.Title,
    episode.viewers = toFloat(row.Viewers),
    episode.dateAired = row.DateAired,
    episode.timestamp = TOINT(row.Timestamp),
    episode.number = TOINT(row.NumberInSeason),
    episode.season = TOINT(row.Season),
    episode.ranking = TOINT(row.Rating)
----

=== What's this `MERGE` all about?

The `MERGE` command does a `MATCH` or `CREATE` i.e. if the node already exists then we'll return it and if it doesn't then we'll create it.

It's quite useful in this context as we may want to run our import script multiple times but don't want to end up with duplicate episodes.

=== Time for some queries


* Find an episode by id
* Find an episode by title

=== What's the query doing under the covers?

We have two ways of exploring what Neo4j is doing when we execute a query.

Prefixing a query with `EXPLAIN` will return the query plan based on statistics the database has. It won't run the query.

Prefixing a query with `PROFILE` will run the query and return the actual query plan that was executed.

Give those a try with the queries we just ran. What do you notice?


=== Index all the things

Let's add an index on a few properties of an episode so that we can find them more quickly in future without having to scan through all the episodes

[source, cypher]
----
CREATE INDEX ON :Episode(id)
----

[source, cypher]
----
CREATE INDEX ON :Episode(title)
----


Now let's import some more data to make it more of a graph and less of a key/value store.

=== Seasons

[source, cypher]
----
LOAD CSV WITH HEADERS FROM "https://raw.githubusercontent.com/mneedham/neo4j-himym/master/data/import/episodes_full.csv" AS row
MERGE (season:Season {number: row.Season})
----

=== Seasons -> Episodes

[source, cypher]
----
LOAD CSV WITH HEADERS FROM "https://raw.githubusercontent.com/mneedham/neo4j-himym/master/data/import/episodes_full.csv" AS row
MATCH (season:Season {number: row.Season})
MATCH (episode:Episode {id: TOINT(row.NumberOverall)})
MERGE (episode)-[:IN_SEASON]->(season)
----


=== Aggregation

* How many episodes were there in each season?


Connecting the episodes together

What sort of queries can we do with a linked list of episodes?

Topics graph

I ran the transcript for each of the episodes through Prismatic's Topic Graph and stored the results into a CSV file. We can add this to the graph as well:

[source, cypher]
----

----


Building the query for an episode's page

* Episode title
* Characters
* Writers

Multi query vs All in one

WITH & COLLECT
